# Generated by Django 4.0.1 on 2022-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('writeup', models.CharField(default='content', max_length=20000)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('News', 'News'), ('Article', 'Article'), ('Protest', 'Protest'), ('Donation', 'Donation')], default='Article', max_length=8)),
            ],
        ),
    ]
